CREATE TABLE IF NOT EXISTS `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `organization_id` int DEFAULT NULL,
  `province_id` int DEFAULT NULL,
  `diocese_id` int DEFAULT NULL,
  `archdeaconry_id` int DEFAULT NULL,
  `deanery_id` int DEFAULT NULL,
  `parish_id` int DEFAULT NULL,
  `role_level` enum('super_admin', 'diocese_admin', 'archdeaconry_admin', 'deanery_admin', 'parish_admin', 'member') DEFAULT 'member',
  `theme_preference` varchar(50) DEFAULT 'light',
  `username` varchar(100) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `first_name` varchar(100) DEFAULT NULL,
  `last_name` varchar(100) DEFAULT NULL,
  `phone_number` varchar(50) DEFAULT NULL,
  `gender` enum('Male', 'Female', 'Other') DEFAULT NULL,
  `account_status` enum('pending', 'active', 'suspended', 'inactive') DEFAULT 'pending',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_login` timestamp NULL DEFAULT NULL,
  `email_verification_token` varchar(255) DEFAULT NULL,
  `email_verified` tinyint(1) DEFAULT 0,
  `password_reset_token` varchar(255) DEFAULT NULL,
  `password_reset_expires` datetime DEFAULT NULL,
  `email_token_expires_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;