-- Migration: Ensure timestamp defaults are correct
ALTER TABLE users 
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE login_attempts 
    MODIFY attempt_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE audit_logs 
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE families 
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE member_groups 
    MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
